"""Build obfuscated thin-client bundles (PyInstaller + encrypted server URL)."""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

from nexusbridge.crypto import encrypt_server_url, generate_build_seed, obfuscate_seed


def write_worker_bundle(
    out_dir: Path,
    *,
    server_url: str,
    build_seed: bytes | None = None,
) -> tuple[bytes, str]:
    """Generate worker_bundle.py with encrypted WSS URL — no plain address in source."""
    out_dir.mkdir(parents=True, exist_ok=True)
    seed = build_seed or generate_build_seed()
    encrypted = encrypt_server_url(server_url, seed)
    obfuscated = obfuscate_seed(seed)

    content = textwrap.dedent(
        f'''\
        """Auto-generated by nexusbridge-build. Do not edit."""
        ENCRYPTED_SERVER_URL = {encrypted!r}
        OBFUSCATED_BUILD_SEED = {obfuscated!r}
        '''
    )
    (out_dir / "worker_bundle.py").write_text(content, encoding="utf-8")
    return seed, encrypted


def build_executable(
    *,
    server_url: str,
    output_dir: Path,
    name: str = "nexusbridge-worker",
    onefile: bool = True,
) -> Path:
    """
    Build a standalone worker .exe/.bin:
    - Server URL encrypted with per-build random seed
    - No JWT secret in binary — user pairs via bot code at first run
    - PyInstaller --strip reduces symbols; add UPX/commercial obfuscators separately
    """
    pkg_root = Path(__file__).resolve().parent
    bundle_dir = output_dir / "_bundle"
    seed_path = output_dir / "build_seed.bin"

    seed, _ = write_worker_bundle(bundle_dir, server_url=server_url)
    seed_path.write_bytes(seed)

    shutil.copy(pkg_root / "worker_app.py", bundle_dir / "worker_app.py")

    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--name",
        name,
        "--distpath",
        str(output_dir / "dist"),
        "--workpath",
        str(output_dir / "build"),
        "--specpath",
        str(output_dir),
        "--clean",
        "--noconfirm",
    ]
    if onefile:
        cmd.append("--onefile")
    cmd.extend(
        [
            "--hidden-import=nexusbridge",
            "--hidden-import=nexusbridge.worker_bundle",
            "--paths",
            str(bundle_dir),
            str(bundle_dir / "worker_app.py"),
        ]
    )

    subprocess.run(cmd, check=True)
    exe_suffix = ".exe" if sys.platform == "win32" else ""
    return output_dir / "dist" / f"{name}{exe_suffix}"


def main_cli() -> None:
    parser = argparse.ArgumentParser(description="Build NexusBridge thin worker")
    parser.add_argument("--server-url", required=True, help="wss://your-bridge-server:8765")
    parser.add_argument("--output-dir", default="worker_dist")
    parser.add_argument("--name", default="nexusbridge-worker")
    parser.add_argument("--bundle-only", action="store_true", help="Only emit encrypted bundle, skip PyInstaller")
    args = parser.parse_args()

    out = Path(args.output_dir)
    if args.bundle_only:
        seed, enc = write_worker_bundle(out, server_url=args.server_url)
        print(f"Bundle written to {out}")
        print(f"Build seed saved — store securely on server side: {out / 'build_seed.bin'}")
        print(f"Encrypted URL length: {len(enc)}")
        return

    try:
        exe = build_executable(server_url=args.server_url, output_dir=out, name=args.name)
        print(f"Built: {exe}")
    except subprocess.CalledProcessError as exc:
        raise SystemExit(f"PyInstaller failed: {exc}") from exc
    except FileNotFoundError:
        print("PyInstaller not installed. Run: pip install nexusbridge[builder]")
        print("Or use --bundle-only to generate encrypted config without building exe.")
        seed, enc = write_worker_bundle(out, server_url=args.server_url)
        print(f"Bundle-only fallback written to {out}")
